### ISSUE TITLE
openpgp: key expired

### ISSUE THREAD

**Issue by maxfd3v** [kristofferahl/terraform-provider-healthchecksio#33] opened 2023-10-05 15:07 UTC
Seeing:
```
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Failed to install provider
│ 
│ Error while installing kristofferahl/healthchecksio v1.9.0: error checking
│ signature: openpgp: key expired
╵

```Is there later version than v1.9.0?

**Comment by maxfd3v** [comment] 2023-10-05 15:09
V 1.10.1 Duh. Apologies

**Comment by maxfd3v** [comment] 2023-10-05 15:12
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Failed to install provider
│ 
│ Error while installing kristofferahl/healthchecksio v1.10.1: error checking
│ signature: openpgp: key expired
╵

**Comment by kristofferahl** [comment] 2023-10-06 18:05
@maxfd3v Thanks for reporting the issue!
At what point are you seeing this error? I tried v1.10.1 but could not reproduce the error.
What version of terraform are you using?

**Comment by kristofferahl** [comment] 2023-10-12 08:13
Is it still an issue @maxfd3v? If not, I'll go ahead and close the issue.

**Comment by guillaumelecerf** [comment] 2023-10-12 09:08
I'm facing the exact same issue:
```
$ terraform --version
Terraform v1.6.0
on linux_amd64
```

```
$ cat versions.tf 
terraform {
  required_version = "~> 1.0"

  required_providers {
    healthchecksio = {
      source  = "kristofferahl/healthchecksio"
      version = "~> 1.9"
    }
  }
}
```

```
$ terraform init
<snip>
- Installing kristofferahl/healthchecksio v1.10.1...
<snip>
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Failed to install provider
│ 
│ Error while installing kristofferahl/healthchecksio v1.10.1: error checking signature: openpgp: key expired
╵
```

**Comment by guillaumelecerf** [comment] 2023-10-12 09:36
Downgrading terraform from 1.6.0 to 1.5.7 resolved the issue.

**Comment by kristofferahl** [comment] 2023-10-13 06:13
@guillaumelecerf  If you have the possibility to upgrade to Terraform 1.6.1, that should also fix the issue.
Judging by comments found [here](https://github.com/hashicorp/terraform/issues/33984#issuecomment-1753160132) this was a bug in 1.6.0. I'll leave the issue open for now to hopefully assist others experiencing the issue.

**Closed as not planned** 2023-11-02 09:02 UTC
